### ISSUE TITLE
need to avoid to specify access key and secret key

### ISSUE THREAD

**Issue by KursLabIgor** [deepakputhraya/monitor-rabbitmq#2]
For accessing to cloudwatch best practice to use ec2 metadata endpoint for getting creds. 
Usually for EC2 specify instance profile with required permissions

**Comment by deepakputhraya** [comment]
I believe the boto3 client takes care of this. Take a look at this for more details - https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configuring-credentials
In the readme, we can be more explicit about setting up credentials.

**Comment by KursLabIgor** [comment]
thanks
